/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.InputStream;
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }
    
    public void setFontFuturaDisplay(JComponent jComboComponent, float fontSize) {
        try {
            // Sử dụng getResourceAsStream để lấy font từ package "font"
            InputStream fontStream = getClass().getResourceAsStream("/font/Futura-Display.ttf");

            if (fontStream != null) {
                Font font = Font.createFont(Font.TRUETYPE_FONT, fontStream).deriveFont(fontSize);
                jComboComponent.setFont(font);
            } else {
                System.err.println("Không tìm thấy file font!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void setFontFutura(JComponent jComboComponent, float fontSize) {
        try {
            // Sử dụng getResourceAsStream để lấy font từ package "font"
            InputStream fontStream = getClass().getResourceAsStream("/font/futur.ttf");

            if (fontStream != null) {
                Font font = Font.createFont(Font.TRUETYPE_FONT, fontStream).deriveFont(fontSize);
                jComboComponent.setFont(font);
            } else {
                System.err.println("Không tìm thấy file font!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void setFontRobotoBold(JComponent jComboComponent, float fontSize) {
        try {
            // Sử dụng getResourceAsStream để lấy font từ package "font"
            InputStream fontStream = getClass().getResourceAsStream("/font/Roboto-Bold.ttf");

            if (fontStream != null) {
                Font font = Font.createFont(Font.TRUETYPE_FONT, fontStream).deriveFont(fontSize);
                jComboComponent.setFont(font);
            } else {
                System.err.println("Không tìm thấy file font!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void setFontRoboto(JComponent jComboComponent, float fontSize) {
        try {
            // Sử dụng getResourceAsStream để lấy font từ package "font"
            InputStream fontStream = getClass().getResourceAsStream("/font/Roboto-Regular.ttf");

            if (fontStream != null) {
                Font font = Font.createFont(Font.TRUETYPE_FONT, fontStream).deriveFont(fontSize);
                jComboComponent.setFont(font);
            } else {
                System.err.println("Không tìm thấy file font!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void setFontHagrid(JComponent jComboComponent, float fontSize) {
        try {
            // Sử dụng getResourceAsStream để lấy font từ package "font"
            InputStream fontStream = getClass().getResourceAsStream("/font/Hagrid-Regular.ttf");

            if (fontStream != null) {
                Font font = Font.createFont(Font.TRUETYPE_FONT, fontStream).deriveFont(fontSize);
                jComboComponent.setFont(font);
            } else {
                System.err.println("Không tìm thấy file font!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_home = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        btn_Account = new javax.swing.JLabel();
        tf_Find = new javax.swing.JTextField();
        btn_Find = new javax.swing.JButton();
        btn_SignInSignUp = new javax.swing.JLabel();
        navigationBar = new javax.swing.JPanel();
        btn_Home1 = new javax.swing.JLabel();
        cbb_menu = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        homePageIMG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jp_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(226, 226, 229));
        header.setPreferredSize(new java.awt.Dimension(1370, 80));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo250x80.png"))); // NOI18N

        btn_Account.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/account_circle_16dp_000000_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N

        tf_Find.setBackground(new java.awt.Color(102, 23, 26));
        tf_Find.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        setFontRoboto(tf_Find, 14f);
        tf_Find.setForeground(new java.awt.Color(226, 226, 229));
        tf_Find.setBorder(null);
        tf_Find.setOpaque(true);
        tf_Find.setPreferredSize(new java.awt.Dimension(700, 30));
        tf_Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_FindActionPerformed(evt);
            }
        });

        btn_Find.setBackground(new java.awt.Color(103, 26, 23));
        btn_Find.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        setFontRoboto(btn_Find, 14f);
        btn_Find.setForeground(new java.awt.Color(226, 226, 229));
        btn_Find.setText("Find");
        btn_Find.setBorder(null);
        btn_Find.setBorderPainted(false);
        btn_Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FindActionPerformed(evt);
            }
        });

        btn_SignInSignUp.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        setFontFutura(btn_SignInSignUp, 20f);
        btn_SignInSignUp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btn_SignInSignUp.setText("Sign In/Sign Up");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(tf_Find, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btn_Find, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btn_SignInSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Account)
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Account, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_Find, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Find, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_SignInSignUp)))
                .addGap(24, 24, 24))
        );

        jp_home.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        navigationBar.setBackground(new java.awt.Color(102, 23, 26));
        navigationBar.setPreferredSize(new java.awt.Dimension(1370, 50));

        btn_Home1.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        setFontFuturaDisplay(btn_Home1, 30f);
        btn_Home1.setForeground(new java.awt.Color(226, 226, 229));
        btn_Home1.setText("Home");

        cbb_menu.setBackground(new java.awt.Color(102, 23, 26));
        cbb_menu.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        setFontFuturaDisplay(cbb_menu, 30f);
        cbb_menu.setForeground(new java.awt.Color(226, 226, 229));
        cbb_menu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menu", "Sign In/Sign up", "Find Movies", "Movies Management", "Screen Room Management" }));
        cbb_menu.setBorder(null);
        cbb_menu.setOpaque(true);
        cbb_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navigationBarLayout = new javax.swing.GroupLayout(navigationBar);
        navigationBar.setLayout(navigationBarLayout);
        navigationBarLayout.setHorizontalGroup(
            navigationBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationBarLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(btn_Home1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbb_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(859, Short.MAX_VALUE))
        );
        navigationBarLayout.setVerticalGroup(
            navigationBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navigationBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navigationBarLayout.createSequentialGroup()
                        .addComponent(btn_Home1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addComponent(cbb_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        cbb_menu.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                JLabel label = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

                // Tính toán chiều rộng cần thiết cho mỗi mục dựa trên nội dung
                FontMetrics metrics = label.getFontMetrics(label.getFont());
                int width = metrics.stringWidth(value.toString()) + 20; // 20 để có thêm khoảng trống
                list.setFixedCellWidth(width);

                return label;
            }
        });

        jp_home.add(navigationBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1370, -1));

        jPanel1.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 72)); // NOI18N
        setFontHagrid(jLabel3, 72f);
        jLabel3.setForeground(new java.awt.Color(213, 60, 56));
        jLabel3.setText("Ciné");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 72)); // NOI18N
        setFontHagrid(jLabel2, 72f);
        jLabel2.setForeground(new java.awt.Color(226, 226, 229));
        jLabel2.setText("Verse");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)))
        );

        jp_home.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, 420, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pic2.png"))); // NOI18N
        jp_home.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        setFontFutura(jLabel4, 32f);
        jLabel4.setForeground(new java.awt.Color(226, 226, 229));
        jLabel4.setText("Where Every Film Finds its Galaxy");
        jp_home.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        setFontFutura(jLabel5, 32f);
        jLabel5.setForeground(new java.awt.Color(226, 226, 229));
        jLabel5.setText("Welcome to the CinéVerse – ");
        jp_home.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, -1, -1));

        homePageIMG.setFont(new java.awt.Font("Segoe UI", 0, 72)); // NOI18N
        homePageIMG.setForeground(new java.awt.Color(103, 23, 26));
        homePageIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cinéverse (2).png"))); // NOI18N
        jp_home.add(homePageIMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        getContentPane().add(jp_home, "card2");

        setSize(new java.awt.Dimension(1380, 776));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_FindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_FindActionPerformed

    private void btn_FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_FindActionPerformed

    private void cbb_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbb_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_Account;
    private javax.swing.JButton btn_Find;
    private javax.swing.JLabel btn_Home1;
    private javax.swing.JLabel btn_SignInSignUp;
    private javax.swing.JComboBox<String> cbb_menu;
    private javax.swing.JPanel header;
    private javax.swing.JLabel homePageIMG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jp_home;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel navigationBar;
    private javax.swing.JTextField tf_Find;
    // End of variables declaration//GEN-END:variables
}
