/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DatabaseConnection.DatabaseConnection;
import font.SetFont;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author kenlee
 */
public class login extends javax.swing.JFrame {
    private SetFont font ;
    private DatabaseConnection databaseconnection;
    

    /**
     * Creates new form login
     */
    public login() {
        font = new SetFont();
        databaseconnection = new DatabaseConnection();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        password = new javax.swing.JLabel();
        staffID = new javax.swing.JLabel();
        txtstaffID = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        login = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 688));
        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(193, 168, 168));
        jPanel5.setBackground(new java.awt.Color(195, 170, 170, 123));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(193, 168, 168));
        jPanel6.setBackground(new java.awt.Color(255, 255, 255 , 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        password.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        font.setFontRoboto(password, 24f);
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password:");
        jPanel6.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 120, 50));

        staffID.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        font.setFontRoboto(staffID, 24f);
        staffID.setForeground(new java.awt.Color(255, 255, 255));
        staffID.setText("Staff ID:");
        jPanel6.add(staffID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 90, 40));

        font.setFontRoboto(txtstaffID, 20f);
        jPanel6.add(txtstaffID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 350, 40));

        font.setFontRoboto(txtpass, 20f);
        jPanel6.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 350, 40));

        btn_login.setBackground(new java.awt.Color(153, 0, 51));
        btn_login.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        font.setFontFutura(btn_login, 20f);
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText(" Log in ");
        btn_login.setAlignmentX(0.5F);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        jPanel6.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 180, 60));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 690, 270));

        login.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        font.setFontFuturaDisplay(login, 50f);
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Log in");
        jPanel5.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 160, 60));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 660, 370));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 690));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 690));

        jPanel1.add(jPanel3, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        try {
            Connection con = DatabaseConnection.getConnection();
           
            
             String staffID =  txtstaffID.getText();
             String password =  txtpass.getText();
             
            if (staffID.isEmpty() || password.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter both Staff ID and Password.");
        
        }
    
             Statement stm = con.createStatement();
             
             String sql = "select * from Staff where sid ='"+staffID+"' and  phone= '"+password+"'";
             ResultSet result =  stm.executeQuery(sql );
              
             if(result.next()){
                 dispose(); // close login page 
                 MainFrame homepage = new MainFrame();
                  homepage.show(); 
             }else {
                  JOptionPane.showMessageDialog(this, " username or password wrong");
                  txtstaffID.setText("");
                  txtpass.setText(""); 
             }
             con.close();
             
      
        } catch (Exception e) {
            System.out.println(e.getMessage()); 
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    
        /* Create and display the form */
        login login = new login();
         login.show();
        
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel login;
    private javax.swing.JLabel password;
    private javax.swing.JLabel staffID;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtstaffID;
    // End of variables declaration//GEN-END:variables
}
