/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import font.SetFont;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author ADMIN
 */
public class MovieManagement extends javax.swing.JFrame {
    private SetFont font = new SetFont();
    /**
     * Creates new form MovieManagement
     */
    public MovieManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navigationBar = new javax.swing.JPanel();
        btn_Home1 = new javax.swing.JLabel();
        cb_Menu = new javax.swing.JComboBox<>();
        logo = new javax.swing.JLabel();
        jl_admin = new javax.swing.JLabel();
        jp_background = new javax.swing.JPanel();
        jp_content = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jl_title = new javax.swing.JLabel();
        tf_title = new javax.swing.JTextField();
        jl_movieID = new javax.swing.JLabel();
        tf_movieID = new javax.swing.JTextField();
        jl_genre = new javax.swing.JLabel();
        tf_genre = new javax.swing.JTextField();
        jl_language = new javax.swing.JLabel();
        tf_language = new javax.swing.JTextField();
        jl_subtitle = new javax.swing.JLabel();
        tf_subtile = new javax.swing.JTextField();
        jl_duration = new javax.swing.JLabel();
        tf_duration = new javax.swing.JTextField();
        jl_releaseDate = new javax.swing.JLabel();
        tf_releaseDate = new javax.swing.JTextField();
        jl_endDate = new javax.swing.JLabel();
        tf_endDate = new javax.swing.JTextField();
        jl_director = new javax.swing.JLabel();
        tf_director = new javax.swing.JTextField();
        jl_cast = new javax.swing.JLabel();
        tf_cast = new javax.swing.JTextField();
        jl_description = new javax.swing.JLabel();
        sp_description = new javax.swing.JScrollPane();
        ta_description = new javax.swing.JTextArea();
        sp_movie = new javax.swing.JScrollPane();
        jt_movie = new javax.swing.JTable();
        jpButton = new javax.swing.JPanel();
        btn_insert = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_ok = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navigationBar.setBackground(new java.awt.Color(102, 23, 26));
        navigationBar.setPreferredSize(new java.awt.Dimension(1370, 50));
        navigationBar.setLayout(null);

        btn_Home1.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        font.setFontFuturaDisplay(btn_Home1, 30f);
        btn_Home1.setForeground(new java.awt.Color(226, 226, 229));
        btn_Home1.setText("Home");
        btn_Home1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_Home1MousePressed(evt);
            }
        });
        navigationBar.add(btn_Home1);
        btn_Home1.setBounds(80, 10, 150, 30);

        cb_Menu.setBackground(new java.awt.Color(102, 23, 26));
        cb_Menu.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        font.setFontFuturaDisplay(cb_Menu, 30f);
        cb_Menu.setForeground(new java.awt.Color(226, 226, 229));
        cb_Menu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menu", "Sign In/Sign up", "Find Movies", "Movies Management", "Screen Room Management" }));
        cb_Menu.setBorder(null);
        cb_Menu.setOpaque(true);
        cb_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_MenuActionPerformed(evt);
            }
        });
        navigationBar.add(cb_Menu);
        cb_Menu.setBounds(230, 10, 240, 30);
        cb_Menu.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                JLabel label = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

                // Tính toán chiều rộng cần thiết cho mỗi mục dựa trên nội dung
                FontMetrics metrics = label.getFontMetrics(label.getFont());
                int width = metrics.stringWidth(value.toString()) + 20; // 20 để có thêm khoảng trống
                list.setFixedCellWidth(width);

                return label;
            }
        });

        logo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo160x50.png"))); // NOI18N
        navigationBar.add(logo);
        logo.setBounds(1210, 0, 160, 50);

        jl_admin.setBackground(new java.awt.Color(255, 255, 255));
        jl_admin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        font.setFontFutura(jl_admin, 24f);
        jl_admin.setForeground(new java.awt.Color(226, 226, 229));
        jl_admin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_admin.setText("ADMIN");
        navigationBar.add(jl_admin);
        jl_admin.setBounds(1100, 20, 100, 30);

        getContentPane().add(navigationBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        jp_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_content.setBackground(new java.awt.Color(226, 226, 229));
        jp_content.setBackground(new Color(226, 226, 229, 123));
        jp_content.setPreferredSize(new java.awt.Dimension(1200, 650));
        jp_content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        font.setFontFutura(jLabel1, 24f);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Movie Management");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(7, 2, 1190, 32);

        jl_title.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        font.setFontRoboto(jl_title, 18f);
        jl_title.setText("Title:");
        jl_title.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel3.add(jl_title);
        jl_title.setBounds(20, 310, 150, 30);

        tf_title.setBackground(new java.awt.Color(226, 226, 229));
        tf_title.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        font.setFontRoboto(tf_title, 14f);
        tf_title.setBorder(null);
        tf_title.setMaximumSize(new java.awt.Dimension(370, 30));
        tf_title.setPreferredSize(new java.awt.Dimension(100, 30));
        tf_title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_titleActionPerformed(evt);
            }
        });
        jPanel3.add(tf_title);
        tf_title.setBounds(170, 310, 610, 30);

        jl_movieID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        font.setFontRoboto(jl_movieID, 18f);
        jl_movieID.setText("Movie ID:");
        jl_movieID.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel3.add(jl_movieID);
        jl_movieID.setBounds(800, 310, 150, 30);

        tf_movieID.setBackground(new java.awt.Color(226, 226, 229));
        tf_movieID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        font.setFontRoboto(tf_movieID, 14f);
        tf_movieID.setBorder(null);
        tf_movieID.setMaximumSize(new java.awt.Dimension(370, 30));
        tf_movieID.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel3.add(tf_movieID);
        tf_movieID.setBounds(950, 310, 220, 30);

        jl_genre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        font.setFontRoboto(jl_genre, 18f);
        jl_genre.setText("Genre:");
        jl_genre.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel3.add(jl_genre);
        jl_genre.setBounds(20, 350, 150, 30);

        tf_genre.setBackground(new java.awt.Color(226, 226, 229));
        tf_genre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        font.setFontRoboto(tf_genre, 14f);
        tf_genre.setBorder(null);
        tf_genre.setMaximumSize(new java.awt.Dimension(370, 30));
        tf_genre.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel3.add(tf_genre);
        tf_genre.setBounds(170, 350, 220, 30);

        jl_language.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        font.setFontRoboto(jl_language, 18f);
        jl_language.setText("Language:");
        jl_language.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel3.add(jl_language);
        jl_language.setBounds(410, 350, 150, 30);

        tf_language.setBackground(new java.awt.Color(226, 226, 229));
        tf_language.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        font.setFontRoboto(tf_language, 14f);
        tf_language.setBorder(null);
        tf_language.setMaximumSize(new java.awt.Dimension(370, 30));
        tf_language.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel3.add(tf_language);
        tf_language.setBounds(560, 350, 220, 30);

        jl_subtitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        font.setFontRoboto(jl_subtitle, 18f);
        jl_subtitle.setText("Subtitle:");
        jl_subtitle.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel3.add(jl_subtitle);
        jl_subtitle.setBounds(800, 350, 150, 30);

        tf_subtile.setBackground(new java.awt.Color(226, 226, 229));
        tf_subtile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        font.setFontRoboto(tf_subtile, 14f);
        tf_subtile.setBorder(null);
        tf_subtile.setMaximumSize(new java.awt.Dimension(370, 30));
        tf_subtile.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel3.add(tf_subtile);
        tf_subtile.setBounds(950, 350, 220, 30);

        jl_duration.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        font.setFontRoboto(jl_duration, 18f);
        jl_duration.setText("Duration:");
        jl_duration.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel3.add(jl_duration);
        jl_duration.setBounds(20, 390, 150, 30);

        tf_duration.setBackground(new java.awt.Color(226, 226, 229));
        tf_duration.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        font.setFontRoboto(tf_duration, 14f);
        tf_duration.setBorder(null);
        tf_duration.setMaximumSize(new java.awt.Dimension(370, 30));
        tf_duration.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel3.add(tf_duration);
        tf_duration.setBounds(170, 390, 220, 30);

        jl_releaseDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        font.setFontRoboto(jl_releaseDate, 18f);
        jl_releaseDate.setText("Release date:");
        jl_releaseDate.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel3.add(jl_releaseDate);
        jl_releaseDate.setBounds(410, 390, 150, 30);

        tf_releaseDate.setBackground(new java.awt.Color(226, 226, 229));
        tf_releaseDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        font.setFontRoboto(tf_releaseDate, 14f);
        tf_releaseDate.setBorder(null);
        tf_releaseDate.setMaximumSize(new java.awt.Dimension(370, 30));
        tf_releaseDate.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel3.add(tf_releaseDate);
        tf_releaseDate.setBounds(560, 390, 220, 30);

        jl_endDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        font.setFontRoboto(jl_endDate, 18f);
        jl_endDate.setText("End date:");
        jl_endDate.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel3.add(jl_endDate);
        jl_endDate.setBounds(800, 390, 150, 30);

        tf_endDate.setBackground(new java.awt.Color(226, 226, 229));
        tf_endDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        font.setFontRoboto(tf_endDate, 14f);
        tf_endDate.setBorder(null);
        tf_endDate.setMaximumSize(new java.awt.Dimension(370, 30));
        tf_endDate.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel3.add(tf_endDate);
        tf_endDate.setBounds(950, 390, 220, 30);

        jl_director.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        font.setFontRoboto(jl_director, 18f);
        jl_director.setText("Director:");
        jl_director.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel3.add(jl_director);
        jl_director.setBounds(20, 430, 150, 30);

        tf_director.setBackground(new java.awt.Color(226, 226, 229));
        tf_director.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        font.setFontRoboto(tf_director, 14f);
        tf_director.setBorder(null);
        tf_director.setMaximumSize(new java.awt.Dimension(370, 30));
        tf_director.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel3.add(tf_director);
        tf_director.setBounds(170, 430, 220, 30);

        jl_cast.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        font.setFontRoboto(jl_cast, 18f);
        jl_cast.setText("Cast:");
        jl_cast.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel3.add(jl_cast);
        jl_cast.setBounds(410, 430, 150, 30);

        tf_cast.setBackground(new java.awt.Color(226, 226, 229));
        tf_cast.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        font.setFontRoboto(tf_cast, 14f);
        tf_cast.setBorder(null);
        tf_cast.setMaximumSize(new java.awt.Dimension(370, 30));
        tf_cast.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel3.add(tf_cast);
        tf_cast.setBounds(560, 430, 610, 30);

        jl_description.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        font.setFontRoboto(jl_description, 18f);
        jl_description.setText("Description:");
        jl_description.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel3.add(jl_description);
        jl_description.setBounds(20, 470, 150, 30);

        sp_description.setBorder(null);

        ta_description.setBackground(new java.awt.Color(226, 226, 229));
        ta_description.setColumns(20);
        ta_description.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        font.setFontRoboto(ta_description, 14f);
        ta_description.setRows(5);
        ta_description.setBorder(null);
        sp_description.setViewportView(ta_description);

        jPanel3.add(sp_description);
        sp_description.setBounds(170, 466, 1000, 110);

        sp_movie.setBorder(null);
        sp_movie.setDoubleBuffered(true);
        sp_movie.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        font.setFontRoboto(sp_movie, 14f);

        jt_movie.setBackground(new java.awt.Color(226, 226, 229));
        jt_movie.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        font.setFontRoboto(jt_movie, 14f);
        jt_movie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movie ID", "Title", "Genre", "Language", "Subtitle", "Duration", "Director", "Cast", "Release Date", "End Date", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sp_movie.setViewportView(jt_movie);

        jPanel3.add(sp_movie);
        sp_movie.setBounds(20, 40, 1150, 260);

        jp_content.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 590));

        jpButton.setOpaque(false);
        jpButton.setPreferredSize(new java.awt.Dimension(1196, 40));
        jpButton.setLayout(new java.awt.GridLayout(1, 5, 70, 30));

        btn_insert.setBackground(new java.awt.Color(102, 23, 26));
        btn_insert.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        font.setFontFutura(btn_insert, 20f);
        btn_insert.setForeground(new java.awt.Color(226, 226, 229));
        btn_insert.setText("Insert");
        btn_insert.setBorder(null);
        btn_insert.setFocusPainted(false);
        btn_insert.setPreferredSize(new java.awt.Dimension(200, 40));
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });
        jpButton.add(btn_insert);

        btn_delete.setBackground(new java.awt.Color(102, 23, 26));
        btn_delete.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        font.setFontFutura(btn_delete, 20f);
        btn_delete.setForeground(new java.awt.Color(226, 226, 229));
        btn_delete.setText("Delete");
        btn_delete.setBorder(null);
        btn_delete.setFocusPainted(false);
        btn_delete.setPreferredSize(new java.awt.Dimension(200, 40));
        jpButton.add(btn_delete);

        btn_edit.setBackground(new java.awt.Color(102, 23, 26));
        btn_edit.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        font.setFontFutura(btn_edit, 20f);
        btn_edit.setForeground(new java.awt.Color(226, 226, 229));
        btn_edit.setText("Edit");
        btn_edit.setBorder(null);
        btn_edit.setFocusPainted(false);
        btn_edit.setPreferredSize(new java.awt.Dimension(200, 40));
        jpButton.add(btn_edit);

        btn_ok.setBackground(new java.awt.Color(102, 23, 26));
        btn_ok.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        font.setFontFutura(btn_ok, 20f);
        btn_ok.setForeground(new java.awt.Color(226, 226, 229));
        btn_ok.setText("OK");
        btn_ok.setBorder(null);
        btn_ok.setFocusPainted(false);
        btn_ok.setPreferredSize(new java.awt.Dimension(200, 40));
        jpButton.add(btn_ok);

        btn_cancel.setBackground(new java.awt.Color(102, 23, 26));
        btn_cancel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        font.setFontFutura(btn_cancel, 20f);
        btn_cancel.setForeground(new java.awt.Color(226, 226, 229));
        btn_cancel.setText("Cancel");
        btn_cancel.setBorder(null);
        btn_cancel.setFocusPainted(false);
        btn_cancel.setPreferredSize(new java.awt.Dimension(150, 40));
        jpButton.add(btn_cancel);

        jp_content.add(jpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 597, 1140, -1));

        jp_background.add(jp_content, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 34, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MovieManagementBG.png"))); // NOI18N
        jp_background.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        getContentPane().add(jp_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1370, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_insertActionPerformed

    private void tf_titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_titleActionPerformed

    private void btn_Home1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Home1MousePressed

    }//GEN-LAST:event_btn_Home1MousePressed

    private void cb_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_MenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_MenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel btn_Home1;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_insert;
    private javax.swing.JButton btn_ok;
    private javax.swing.JComboBox<String> cb_Menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jl_admin;
    private javax.swing.JLabel jl_cast;
    private javax.swing.JLabel jl_description;
    private javax.swing.JLabel jl_director;
    private javax.swing.JLabel jl_duration;
    private javax.swing.JLabel jl_endDate;
    private javax.swing.JLabel jl_genre;
    private javax.swing.JLabel jl_language;
    private javax.swing.JLabel jl_movieID;
    private javax.swing.JLabel jl_releaseDate;
    private javax.swing.JLabel jl_subtitle;
    private javax.swing.JLabel jl_title;
    private javax.swing.JPanel jpButton;
    private javax.swing.JPanel jp_background;
    private javax.swing.JPanel jp_content;
    private javax.swing.JTable jt_movie;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel navigationBar;
    private javax.swing.JScrollPane sp_description;
    private javax.swing.JScrollPane sp_movie;
    private javax.swing.JTextArea ta_description;
    private javax.swing.JTextField tf_cast;
    private javax.swing.JTextField tf_director;
    private javax.swing.JTextField tf_duration;
    private javax.swing.JTextField tf_endDate;
    private javax.swing.JTextField tf_genre;
    private javax.swing.JTextField tf_language;
    private javax.swing.JTextField tf_movieID;
    private javax.swing.JTextField tf_releaseDate;
    private javax.swing.JTextField tf_subtile;
    private javax.swing.JTextField tf_title;
    // End of variables declaration//GEN-END:variables
}
