/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import font.SetFont;

/**
 *
 * @author ADMIN
 */
public class ScreenRoomManagementPanel extends javax.swing.JPanel {
    private SetFont font;
    /**
     * Creates new form ScreenRoomManagementPanel
     */
    public ScreenRoomManagementPanel() {
        font = new SetFont();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_content = new javax.swing.JPanel();
        jp_infor = new javax.swing.JPanel();
        jl_screenRoomManagement = new javax.swing.JLabel();
        sp_screenRoom = new javax.swing.JScrollPane();
        jt_screenRoom = new javax.swing.JTable();
        jl_roomID = new javax.swing.JLabel();
        tf_roomID = new javax.swing.JTextField();
        jl_roomName = new javax.swing.JLabel();
        tf_roomName = new javax.swing.JTextField();
        jl_totalSeats = new javax.swing.JLabel();
        tf_totalSeats = new javax.swing.JTextField();
        jl_screenType = new javax.swing.JLabel();
        tf_screenType = new javax.swing.JTextField();
        jl_equipment = new javax.swing.JLabel();
        tf_equipment = new javax.swing.JTextField();
        jl_note = new javax.swing.JLabel();
        sp_note = new javax.swing.JScrollPane();
        ta_note = new javax.swing.JTextArea();
        jl_status = new javax.swing.JLabel();
        rb_available = new javax.swing.JRadioButton();
        rb_notAvailable = new javax.swing.JRadioButton();
        jpButton = new javax.swing.JPanel();
        btn_insert = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_ok = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_content.setBackground(new java.awt.Color(226, 226, 229));
        jp_content.setBackground(new java.awt.Color(226, 226, 229, 123));
        jp_content.setPreferredSize(new java.awt.Dimension(1200, 650));
        jp_content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_infor.setBackground(new java.awt.Color(255, 255, 255));
        jp_infor.setOpaque(false);
        jp_infor.setLayout(null);

        jl_screenRoomManagement.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        font.setFontFutura(jl_screenRoomManagement, 24f);
        jl_screenRoomManagement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_screenRoomManagement.setText("Screen Room Management");
        jp_infor.add(jl_screenRoomManagement);
        jl_screenRoomManagement.setBounds(7, 2, 1190, 32);

        sp_screenRoom.setBorder(null);
        sp_screenRoom.setDoubleBuffered(true);
        sp_screenRoom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        font.setFontRoboto(sp_screenRoom, 14f);

        jt_screenRoom.setBackground(new java.awt.Color(226, 226, 229));
        jt_screenRoom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        font.setFontRoboto(jt_screenRoom, 14f);
        jt_screenRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room ID", "Room Name", "Total Seats", "Screen Type", "Equipment", "Status", "Note"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sp_screenRoom.setViewportView(jt_screenRoom);

        jp_infor.add(sp_screenRoom);
        sp_screenRoom.setBounds(20, 40, 1150, 350);

        jl_roomID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        font.setFontRoboto(jl_roomID, 18f);
        jl_roomID.setText("Room ID:");
        jl_roomID.setPreferredSize(new java.awt.Dimension(150, 16));
        jp_infor.add(jl_roomID);
        jl_roomID.setBounds(20, 400, 150, 30);

        tf_roomID.setBackground(new java.awt.Color(226, 226, 229));
        tf_roomID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        font.setFontRoboto(tf_roomID, 14f);
        tf_roomID.setBorder(null);
        tf_roomID.setMaximumSize(new java.awt.Dimension(370, 30));
        tf_roomID.setPreferredSize(new java.awt.Dimension(100, 30));
        jp_infor.add(tf_roomID);
        tf_roomID.setBounds(170, 400, 220, 30);

        jl_roomName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        font.setFontRoboto(jl_roomName, 18f);
        jl_roomName.setText("Room name:");
        jl_roomName.setPreferredSize(new java.awt.Dimension(150, 16));
        jp_infor.add(jl_roomName);
        jl_roomName.setBounds(410, 400, 150, 30);

        tf_roomName.setBackground(new java.awt.Color(226, 226, 229));
        tf_roomName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        font.setFontRoboto(tf_roomName, 14f);
        tf_roomName.setBorder(null);
        tf_roomName.setMaximumSize(new java.awt.Dimension(370, 30));
        tf_roomName.setPreferredSize(new java.awt.Dimension(100, 30));
        tf_roomName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_roomNameActionPerformed(evt);
            }
        });
        jp_infor.add(tf_roomName);
        tf_roomName.setBounds(560, 400, 220, 30);

        jl_totalSeats.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        font.setFontRoboto(jl_totalSeats, 18f);
        jl_totalSeats.setText("Total seats:");
        jl_totalSeats.setPreferredSize(new java.awt.Dimension(150, 16));
        jp_infor.add(jl_totalSeats);
        jl_totalSeats.setBounds(800, 400, 150, 30);

        tf_totalSeats.setBackground(new java.awt.Color(226, 226, 229));
        tf_totalSeats.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        font.setFontRoboto(tf_totalSeats, 14f);
        tf_totalSeats.setBorder(null);
        tf_totalSeats.setMaximumSize(new java.awt.Dimension(370, 30));
        tf_totalSeats.setPreferredSize(new java.awt.Dimension(100, 30));
        jp_infor.add(tf_totalSeats);
        tf_totalSeats.setBounds(950, 400, 220, 30);

        jl_screenType.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        font.setFontRoboto(jl_screenType, 18f);
        jl_screenType.setText("Screen Type:");
        jl_screenType.setPreferredSize(new java.awt.Dimension(150, 16));
        jp_infor.add(jl_screenType);
        jl_screenType.setBounds(20, 440, 150, 30);

        tf_screenType.setBackground(new java.awt.Color(226, 226, 229));
        tf_screenType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        font.setFontRoboto(tf_screenType, 14f);
        tf_screenType.setBorder(null);
        tf_screenType.setMaximumSize(new java.awt.Dimension(370, 30));
        tf_screenType.setPreferredSize(new java.awt.Dimension(100, 30));
        jp_infor.add(tf_screenType);
        tf_screenType.setBounds(170, 440, 220, 30);

        jl_equipment.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        font.setFontRoboto(jl_equipment, 18f);
        jl_equipment.setText("Equipment:");
        jl_equipment.setPreferredSize(new java.awt.Dimension(150, 16));
        jp_infor.add(jl_equipment);
        jl_equipment.setBounds(410, 440, 150, 30);

        tf_equipment.setBackground(new java.awt.Color(226, 226, 229));
        tf_equipment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        font.setFontRoboto(tf_equipment, 14f);
        tf_equipment.setBorder(null);
        tf_equipment.setMaximumSize(new java.awt.Dimension(370, 30));
        tf_equipment.setPreferredSize(new java.awt.Dimension(100, 30));
        jp_infor.add(tf_equipment);
        tf_equipment.setBounds(560, 440, 220, 30);

        jl_note.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        font.setFontRoboto(jl_note, 18f);
        jl_note.setText("Note:");
        jl_note.setPreferredSize(new java.awt.Dimension(150, 16));
        jp_infor.add(jl_note);
        jl_note.setBounds(20, 480, 150, 30);

        sp_note.setBorder(null);

        ta_note.setBackground(new java.awt.Color(226, 226, 229));
        ta_note.setColumns(20);
        ta_note.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        font.setFontRoboto(ta_note, 14f);
        ta_note.setRows(5);
        ta_note.setBorder(null);
        ta_note.setPreferredSize(new java.awt.Dimension(260, 80));
        sp_note.setViewportView(ta_note);

        jp_infor.add(sp_note);
        sp_note.setBounds(170, 480, 1000, 110);

        jl_status.setBackground(new java.awt.Color(255, 255, 255));
        jl_status.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        font.setFontRoboto(jl_status, 18f);
        jl_status.setText("Status:");
        jl_status.setPreferredSize(new java.awt.Dimension(150, 16));
        jp_infor.add(jl_status);
        jl_status.setBounds(800, 440, 90, 30);

        rb_available.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        font.setFontRoboto(rb_available, 14f);
        rb_available.setText("Available");
        rb_available.setBorder(null);
        rb_available.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_availableActionPerformed(evt);
            }
        });
        jp_infor.add(rb_available);
        rb_available.setBounds(900, 440, 130, 30);

        rb_notAvailable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        font.setFontRoboto(rb_notAvailable, 14f);
        rb_notAvailable.setText("Not Available");
        rb_notAvailable.setBorder(null);
        jp_infor.add(rb_notAvailable);
        rb_notAvailable.setBounds(1040, 440, 130, 30);

        jp_content.add(jp_infor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 590));

        jpButton.setOpaque(false);
        jpButton.setPreferredSize(new java.awt.Dimension(1196, 40));
        jpButton.setLayout(new java.awt.GridLayout(1, 5, 70, 30));

        btn_insert.setBackground(new java.awt.Color(102, 23, 26));
        btn_insert.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        font.setFontRobotoBold(btn_insert, 20f);
        btn_insert.setForeground(new java.awt.Color(226, 226, 229));
        btn_insert.setText("Insert");
        btn_insert.setBorder(null);
        btn_insert.setFocusPainted(false);
        btn_insert.setPreferredSize(new java.awt.Dimension(200, 40));
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });
        jpButton.add(btn_insert);

        btn_delete.setBackground(new java.awt.Color(102, 23, 26));
        btn_delete.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(226, 226, 229));
        btn_delete.setText("Delete");
        btn_delete.setBorder(null);
        btn_delete.setFocusPainted(false);
        btn_delete.setPreferredSize(new java.awt.Dimension(200, 40));
        jpButton.add(btn_delete);

        btn_edit.setBackground(new java.awt.Color(102, 23, 26));
        btn_edit.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(226, 226, 229));
        btn_edit.setText("Edit");
        btn_edit.setBorder(null);
        btn_edit.setFocusPainted(false);
        btn_edit.setPreferredSize(new java.awt.Dimension(200, 40));
        jpButton.add(btn_edit);

        btn_ok.setBackground(new java.awt.Color(102, 23, 26));
        btn_ok.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btn_ok.setForeground(new java.awt.Color(226, 226, 229));
        btn_ok.setText("OK");
        btn_ok.setBorder(null);
        btn_ok.setFocusPainted(false);
        btn_ok.setPreferredSize(new java.awt.Dimension(200, 40));
        jpButton.add(btn_ok);

        btn_cancel.setBackground(new java.awt.Color(102, 23, 26));
        btn_cancel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(226, 226, 229));
        btn_cancel.setText("Cancel");
        btn_cancel.setBorder(null);
        btn_cancel.setFocusPainted(false);
        btn_cancel.setPreferredSize(new java.awt.Dimension(150, 40));
        jpButton.add(btn_cancel);

        jp_content.add(jpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 597, 1140, -1));

        add(jp_content, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 19, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.png"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tf_roomNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_roomNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_roomNameActionPerformed

    private void rb_availableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_availableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_availableActionPerformed

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_insertActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_insert;
    private javax.swing.JButton btn_ok;
    private javax.swing.JLabel jl_equipment;
    private javax.swing.JLabel jl_note;
    private javax.swing.JLabel jl_roomID;
    private javax.swing.JLabel jl_roomName;
    private javax.swing.JLabel jl_screenRoomManagement;
    private javax.swing.JLabel jl_screenType;
    private javax.swing.JLabel jl_status;
    private javax.swing.JLabel jl_totalSeats;
    private javax.swing.JPanel jpButton;
    private javax.swing.JPanel jp_content;
    private javax.swing.JPanel jp_infor;
    private javax.swing.JTable jt_screenRoom;
    private javax.swing.JRadioButton rb_available;
    private javax.swing.JRadioButton rb_notAvailable;
    private javax.swing.JScrollPane sp_note;
    private javax.swing.JScrollPane sp_screenRoom;
    private javax.swing.JTextArea ta_note;
    private javax.swing.JTextField tf_equipment;
    private javax.swing.JTextField tf_roomID;
    private javax.swing.JTextField tf_roomName;
    private javax.swing.JTextField tf_screenType;
    private javax.swing.JTextField tf_totalSeats;
    // End of variables declaration//GEN-END:variables
}
