/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import font.SetFont;
import java.awt.event.MouseListener;
import javax.swing.JLabel;

/**
 *
 * @author ADMIN
 */
public class SideBar extends javax.swing.JPanel {
    private SetFont font;
    /**
     * Creates new form SideBar
     */
    public SideBar() {
        font = new SetFont();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_sideBar = new javax.swing.JPanel();
        btn_home = new javax.swing.JLabel();
        btn_filter = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_screenRoom = new javax.swing.JLabel();
        btn_staff = new javax.swing.JLabel();
        btn_showTime = new javax.swing.JLabel();
        btn_ticket = new javax.swing.JLabel();
        btn_account = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btn_statistic = new javax.swing.JLabel();
        btn_movie = new javax.swing.JLabel();
        btn_exit = new javax.swing.JLabel();

        jp_sideBar.setBackground(new java.awt.Color(71, 15, 17));

        btn_home.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        font.setFontFuturaDisplay(btn_home, 28f);
        btn_home.setForeground(new java.awt.Color(226, 226, 229));
        btn_home.setText("Home");

        btn_filter.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        font.setFontFuturaDisplay(btn_filter, 28f);
        btn_filter.setForeground(new java.awt.Color(226, 226, 229));
        btn_filter.setText("Filter");

        btn_screenRoom.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        font.setFontFuturaDisplay(btn_screenRoom, 28f);
        btn_screenRoom.setForeground(new java.awt.Color(226, 226, 229));
        btn_screenRoom.setText("Screen Rooms");

        btn_staff.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        font.setFontFuturaDisplay(btn_staff, 28f);
        btn_staff.setForeground(new java.awt.Color(226, 226, 229));
        btn_staff.setText("Staffs");

        btn_showTime.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        font.setFontFuturaDisplay(btn_showTime, 28f);
        btn_showTime.setForeground(new java.awt.Color(226, 226, 229));
        btn_showTime.setText("Show Time");

        btn_ticket.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        font.setFontFuturaDisplay(btn_ticket, 28f);
        btn_ticket.setForeground(new java.awt.Color(226, 226, 229));
        btn_ticket.setText("Ticket");

        btn_account.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        font.setFontFuturaDisplay(btn_account, 28f);
        btn_account.setForeground(new java.awt.Color(226, 226, 229));
        btn_account.setText("Account");

        btn_statistic.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        font.setFontFuturaDisplay(btn_statistic, 28f);
        btn_statistic.setForeground(new java.awt.Color(226, 226, 229));
        btn_statistic.setText("Statistic");

        btn_movie.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        font.setFontFuturaDisplay(btn_movie, 28f);
        btn_movie.setForeground(new java.awt.Color(226, 226, 229));
        btn_movie.setText("Movies");

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_exit.png"))); // NOI18N

        javax.swing.GroupLayout jp_sideBarLayout = new javax.swing.GroupLayout(jp_sideBar);
        jp_sideBar.setLayout(jp_sideBarLayout);
        jp_sideBarLayout.setHorizontalGroup(
            jp_sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_sideBarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jp_sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_filter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_screenRoom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_staff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_movie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_showTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_account, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ticket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_statistic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_sideBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp_sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_exit, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jp_sideBarLayout.setVerticalGroup(
            jp_sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_exit)
                .addGap(15, 15, 15)
                .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btn_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btn_movie, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btn_screenRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btn_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btn_showTime, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btn_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btn_account, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btn_statistic, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp_sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp_sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void showSideBar(){
        this.setVisible(true);
        this.setEnabled(true);
    }
    
    public void hideSidebar(){
        this.setVisible(false);
        this.setEnabled(false);
    }
    
    public void setMouseListener(MouseListener ml){
        btn_filter.addMouseListener(ml);
        btn_home.addMouseListener(ml);
        btn_movie.addMouseListener(ml);
        btn_screenRoom.addMouseListener(ml);
        btn_showTime.addMouseListener(ml);
        btn_account.addMouseListener(ml);
        btn_staff.addMouseListener(ml);
        btn_statistic.addMouseListener(ml);
        btn_ticket.addMouseListener(ml);
        
        btn_exit.addMouseListener(ml);
    }

    public JLabel getBtn_account() {
        return btn_account;
    }

    public JLabel getBtn_exit() {
        return btn_exit;
    }

    public JLabel getBtn_filter() {
        return btn_filter;
    }

    public JLabel getBtn_home() {
        return btn_home;
    }

    public JLabel getBtn_movie() {
        return btn_movie;
    }

    public JLabel getBtn_screenRoom() {
        return btn_screenRoom;
    }

    public JLabel getBtn_showTime() {
        return btn_showTime;
    }

    public JLabel getBtn_staff() {
        return btn_staff;
    }

    public JLabel getBtn_statistic() {
        return btn_statistic;
    }

    public JLabel getBtn_ticket() {
        return btn_ticket;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_account;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JLabel btn_filter;
    private javax.swing.JLabel btn_home;
    private javax.swing.JLabel btn_movie;
    private javax.swing.JLabel btn_screenRoom;
    private javax.swing.JLabel btn_showTime;
    private javax.swing.JLabel btn_staff;
    private javax.swing.JLabel btn_statistic;
    private javax.swing.JLabel btn_ticket;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jp_sideBar;
    // End of variables declaration//GEN-END:variables
}
